language: python
python:
  - "2.7"
# command to install dependencies
before_install:
  - python --version
  - pip --version
# command to run tests
install:
  - pip install pytest --upgrade
  - pip install pytest-cov
  - pip install coveralls
script:
  - py.test --cov-report term-missing --cov=myassert
after_success:
  - coveralls